---
openapi: 3.0.0
info:
  title: API do app pixel
  description: API do app pixel
  contact:
    email: lucas.engen.cc@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: localhost:3001
    description: Instância local do pixel server
tags:
  - name: comuns
    description: Rotas que não exigem token
  - name: trancadas
    description: Rotas que exigem o token de login
paths:
  /health:
    get:
      tags:
        - comuns
      summary: obtém status do servidor
      description: |
        Essa rota permite verificar se o servidor está em execução
      operationId: searchInventory
      responses:
        "200":
          description: O servidor está online
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthData"
        "400":
          description: bad input parameter
  /login:
    post:
      tags:
        - comuns
      summary: efetua o login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"

      responses:
        "200":
          description: usuário fez login
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LoginResult"

  /pixel/new:
    post:
      tags:
        - trancadas
      summary: cria um novo pixel
      parameters:
        - in: header
          name: X-Access-Token
          description: token de usuário obtido após fazer login
          schema:
            type: string
          required: true

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CreatePixelRequest"

      responses:
        "200":
          description: o pixel foi criado

  /features:
    get:
      tags:
        - comuns
      summary: obtém a lista de todos as características dos pixels
      description: Retorna a lista de características possíveis de editar em um pixel

      responses:
        "200":
          description: a lista de características foi obtida com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedPixelBody"
        "500":
          description: erro interno do servidor. verifique se o banco de dados está funcionando
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericError"

  /pixel/by-mail:
    get:
      tags:
        - comuns
      summary: retorna os pixels de um usuário
      parameters:
        - in: query
          name: mail
          schema:
            type: string
          required: true

      responses:
        "200":
          description: O usuário possui um pixel associado a ele
        "400":
          description: a requisição está inválida (nenhum parâmetro de busca foi passado)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GenericError"
        "404":
          description: usuário não foi encontrado/usuário não possui nenhum pixel
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GenericError"

  /pixel/{pixelId}/feed:
    post:
      tags:
        - comuns
      summary: alimenta um pixel pelo id
      description: Pesquisa por um pixel com um determinado id e alimenta-o
      parameters:
        - name: "pixelId"
          in: "path"
          description: "id do pixel a ser alimentado"
          required: true
          content:
            application/json:
              schema:
                type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeedPixelBody"

      responses:
        "200":
          description: o pixel foi alimentado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedPixelBody"

        "404":
          description: o pixel não foi encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericError"

  /register:
    post:
      tags:
        - comuns
      summary: cria um usuário
      description: Cria um novo usuário no sisema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"

      responses:
        "200":
          description: "usuário criado com sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterUserResponse"

        "500":
          description: "falha ao criar usuário (usuário já existe ou banco pode estar fora do ar)"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericError"

  /pixel/{pixelId}/features:
    get:
      tags:
        - comuns
      summary: obtém as características de um pixel
      parameters:
        - in: path
          name: pixelId
          schema:
            type: integer
          description: ID do pixel
          required: true

      responses:
        "200":
          description: as características foram obtidas com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedPixelBody"

        "404":
          description: o pixel não existe
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericError"

  /team/new:
    post:
      tags:
        - comuns
      summary: cria um novo time

      responses:
        "200":
          description: o time foi criado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamCreated"

components:
  schemas:
    TeamCreated:
      type: object
      properties:
        id:
          type: integer
          description: ID do time criado
        createdAt:
          type: string
          description: data de criação
        updatedAt:
          type: string
          description: data de atualização

    RegisterUserResponse:
      type: object
      properties:
        id:
          type: integer
          description: ID do usuário criado
          example: 1
        email:
          type: string
          description: email do usuário criado
          example: test@email.org

    GenericError:
      type: object
      properties:
        error:
          type: string
          description: mensagem de erro
          example: "mensagem de erro qualquer"

    HealthData:
      type: object
      properties:
        message:
          type: string
          description: mensagem contendo o PID do servidor
          example: server running with pid 10

    LoginRequest:
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
          description: email do usuário
          example: email@test.com
        password:
          type: string
          description: senha do usuário
          example: test1234@

    LoginResult:
      required:
        - email
        - id
      type: object
      properties:
        id:
          type: integer
          description: id do usuário criado
        email:
          type: string
          description: email do usuário criado

    CreatePixelRequest:
      required:
        - name
        - eye
        - color
      type: object
      properties:
        name:
          type: string
          example: pixel 1
        eye:
          type: string
          example: olho 1
        color:
          type: string
          example: "#ff0011"

    FeedPixelBody:
      required:
        - visibility
        - match
        - control
        - consistence
        - recognition
        - efficiency
        - minimalism
        - error_prevention
      properties:
        visibility:
          type: integer
          description: visibilidade
          example: 0
        match:
          type: integer
          description: correspondência
          example: 10
        control:
          type: integer
          description: controle
          example: 1
        consistence:
          type: integer
          description: consistência
          example: 2
        recognition:
          type: integer
          description: reconhecimento
          example: 3
        efficiency:
          type: integer
          description: eficiência
          example: 0
        minimalism:
          type: integer
          description: minimalismo
          example: 0
        error_prevention:
          type: integer
          description: prevenção de erros
          example: 0
