version: "3.8"

services:
  banco:
    image: bitnami/postgresql:latest
    container_name: pixel-api-database
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432" # mapeia a porta 5432 do container para a DB_PORT local
    networks:
      - rede-interna
    volumes:
      - postgresdb_vol:/var/lib/postgresql/data

  api:
    container_name: pixel-api
    build: .
    restart: always
    depends_on:
      - banco
    networks:
      - rede-interna
    links:
      - banco:${DB_HOST}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}

volumes:
  node_modules_vol:
  postgresdb_vol:

networks:
  rede-interna:
    name: rede-interna
    driver: bridge
