version: "3.8"

services:
  banco:
    image: bitnami/postgresql:13
    container_name: pixel-api-database
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432" # mapeia a porta 5432 do container para a DB_PORT local
    networks:
      - rede-interna
    volumes:
      - postgresdb_vol:/var/lib/postgresql/data

  api:
    container_name: pixel-api
    build: .
    restart: always
    depends_on:
      - banco
    networks:
      - rede-interna
    links:
      - banco
    ports:
      - "${APP_PORT}:${APP_PORT}"

volumes:
  node_modules_vol:
  postgresdb_vol:

networks:
  rede-interna:
    name: rede-interna
    driver: bridge
